services:
  redis:
    image: redis:6-alpine
    container_name: redis
    ports:
      - "${RQ_DEFAULT_PORT}:6379"

  db:
    image: postgres:14-alpine
    container_name: postgres
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rq_worker:
    build: .
    volumes:
      - .:/app
    container_name: rq_worker
    command: python manage.py rqworker --with-scheduler
    depends_on:
      - redis
      - db
    env_file:
      - .env
    environment:
      - RQ_DEFAULT_HOST=redis
      - RQ_DEFAULT_PORT=6379

volumes:
  pgdata:
    driver: local