# Generated by Django 6.0 on 2026-03-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0012_alter_invoice_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='price',
            field=models.DecimalField(decimal_places=4, help_text='Price per unit', max_digits=10),
        ),
    ]
